### ISSUE TITLE
tag subcommand fails with unhelpful error message when the tag exists

### ISSUE THREAD

**Issue by NathanReb** [ocamllabs/dune-release#225]
Running `dune-release tag` fails if the tag already exists:
```
$ dune-release tag
[-] Extracting tag from first entry in CHANGES.md
[-] Using tag "v0.2.0+test"
[?] Create git tag v0.2.0+test for HEAD? [Y/n]

dune-release: [ERROR] The following command exited with code 128:
                      git --git-dir .git tag -a -m Distribution v0.2.0+test
                      v0.2.0+test HEAD
```

This isn't very helpful. I think that to the very least we should:
1. clean up the error logs in those cases, I'm really not so fond of `Logs` default error reporting.
2. Show external commands stderr/stdout when they fail

In this particular case we could go even further and check whether the tag exists before tagging.If it exists and points to the current `HEAD`, we could successfully exit, informing the user that the tag already exists and points to the right place. If it points to somewhere else, we could fail and inform the user why we did.

**Comment by pitag-ha** [comment]
I've split this issue into three (the other two parts being  #228 and #229 treating point 1. and 2. described above, respectively). So now, this issue is narrowed down to improving the `tag` command error and status logs by considering different cases. Concretely, when the provided tag (default: version number) already exists, we should check if the commit it points to corresponds to the provided commit-ish (default: `HEAD`) and adjust the error/status logs accordingly.
