### ISSUE TITLE
Updating PR seems to failure

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/dune-release#282]
When redoing a release, the github API returns an error after dune-release tries to update the PR.

```
[-] Opening pull request to merge branch release-dune-2.7.1 of git@github.com:rgrinberg/opam-repository into ocaml/opam-repository
dune-release: [ERROR] Could not retrieve pull request URL from response, unexpected Github API error: "Validation Failed"
```

**Comment by gpetiot** [comment]
Hi, dune-release doesn't support PR updates for now, if you already opened a PR and wish to modify it you will have to close it first before running dune-release again. I'm currently having a look at making draft release possible so that could fix this issue.

On a separate note, the error message could be improved!

**Comment by gpetiot** [comment]
duplicate of #230
