### ISSUE TITLE
The repo is dirty. The distribution archive may be inconsistent

### ISSUE THREAD

**Issue by shakthimaan** [ocamllabs/dune-release#340]
I am trying to submit a package `rungen` to opam.ocaml.org using the following steps:
https://ocaml-explore.netlify.app/workflows/publishing-a-new-package-on-opam/#for-dune-users

`dune build` and `dune-release lint` are fine.
```
$ dune-release lint 
[ OK ] File README is present.
[ OK ] File LICENSE is present.
[ OK ] File CHANGES is present.
[ OK ] File opam is present.
[ OK ] lint opam file rungen.opam.
[ OK ] opam field description is present
[ OK ] opam fields homepage and dev-repo can be parsed by dune-release
[ OK ] Skipping doc field linting, no doc field found
[ OK ] lint /home/shakthi/rungen success
```
When I use `dune-release distrib`, I get an error:
```
$ dune-release distrib
[-] Building source archive
[+] Wrote archive _build/rungen-Changelog.tbz[-] Linting distrib in _build/rungen-Changelog
[ OK ] File README is present.
[ OK ] File LICENSE is present.
[ OK ] File CHANGES is present.
[ OK ] File opam is present.
[ OK ] lint opam file rungen.opam.
[ OK ] opam field description is present
[ OK ] opam fields homepage and dev-repo can be parsed by dune-release
[ OK ] Skipping doc field linting, no doc field found
[ OK ] lint _build/rungen-Changelog success[-] Building package in _build/rungen-Changelog
Done: 19/23 (jobs: 1)[ OK ] package builds[-] Running package tests in _build/rungen-Changelog
Done: 0/0 (jobs: 0)[ OK ] package tests[+] Distribution for rungen Changelog
[+] Commit b6ff5cef2cd7ed1631e568de8be13583866928d4
[+] Archive _build/rungen-Changelog.tbz
dune-release: [WARNING] The repo is dirty. The distribution archive may be
                        inconsistent.
```
Why does it say that the `repo is dirty`? It clearly created _build which is not tracked by Git. I checked `git status`:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	_build/

nothing added to commit but untracked files present (use "git add" to track)
```
The same warning with `dune-release opam pkg`:
```
$ dune-release opam pkg 
[-] Creating opam package description for rungen
[+] Wrote opam package description _build/rungen.Changelog/opam
dune-release: [WARNING] The repo is dirty. The opam package may be
                        inconsistent with the distribution.
```
When I try to submit the package to opam for review, it asks for opam-repository information. What should be the required values to set this up locally?
```
$ dune-release opam submit 
/home/shakthi/.config/dune/release.yml does not exist!
Please answer a few questions to help me create it for you:What is your GitHub ID?
[press ENTER to use 'ocaml-bench']What is your fork of ocaml/opam-repository? (you should have write access).
[press ENTER to use 'git@github.com:ocaml-bench/opam-repository']Where on your filesystem did you clone that repository?
[press ENTER to use '/home/shakthi/git/opam-repository'][-] Submitting 
[-] Preparing pull request to ocaml/opam-repository
dune-release: [ERROR] /home/shakthi/git/opam-repository is not a valid Git repository.
```
My rungen.opam file contents are as follows:
```
cat rungen.opam 
opam-version: "2.0"
name: "rungen"
version: "0.1"
synopsis: "Generates dune files to run benchmarks from centralised config"
maintainer: "Sadiq Jaffer <sadiq@toao.com>"
authors: "Sadiq Jaffer <sadiq@toao.com>"
license: "MIT"
homepage: "https://github.com/ocaml-bench/rungen"
bug-reports: "https://github.com/ocaml-bench/rungen/issues"
dev-repo: "git+https://github.com/shakthimaan/rungen"
depends: [ "ocaml" "yojson" "sexplib0" ]
build: [
  ["dune" "build" "-p" name]
]
description: """
The rungen utility generates dune files to execute
[Sandmark](https://github.com/ocaml-bench/sandmark) benchmarks.
"""
```
Please advice.

**Comment by NathanReb** [comment]
> Why does it say that the repo is dirty

That's because the repo contains uncommitted changes or untracked files. It is just a warning and not an error, dune-release will simply go on there and most likely do the right thing. The purpose of this warning is to let you know that you might release something different than what you have locally, e.g. if you forgot to commit changes to your opam file, you probably want to know about it.

Here it is true that the _build was generated by dune-release itself but considering your project uses dune, your `.gitignore` should contain `_build` and that will both fix this warning and improbe your dev experience!

> When I try to submit the package to opam for review, it asks for opam-repository information. What should be the required values to set this up locally?

This the required information for dune-release to release packages for you. Your Github ID should be your own github handle, so `shakthimaan`, your opam-repository fork should most likely be `git@github.com:shakthimaan/opam-repository.git` (remember to fork https://github.com/ocaml/opam-repository first if you haven't done it yet). Finally you'll need a local clone of opam-repository on your machine and and answer that last question with the path to this clone.

To clarify a bit why this is all needed, when publishing your package to opam-repository, dune-release will move into your local clone of it, create branch there, commit the new opam file(s) to the right place, push this to your fork and then open a PR to merge this branch into the upstream opam-repository.

There's definitely room for improvement here, in particular it could create the fork for you if you haven't created it yet and could also clone the repo for you the first time as well.

We'll work on improving this but in the meantime I hope this answers all your questions and will allow you to complete your release. Please don't hesitate to reach out again if you need further help or have any other questions!

**Comment by shakthimaan** [comment]
Thanks for your detailed reply. I am now using my `shakthimaan` GitHub handle, and updated the .opam file to use my repository. I have also forked `opam-repository` and cloned it locally. `dune-release publish` and `dune-release opam pkg` are fine.
```
$ dune-release publish 
[-] Skipping documentation publication for package rungen: no doc field in rungen.opam
[-] Publishing distribution
[-] Publishing to github
[?] Push tag Changelog to git@github.com:shakthimaan/rungen? [Y/n]
Y
[-] Pushing tag Changelog to git@github.com:shakthimaan/rungen
[?] Create release Changelog on git@github.com:shakthimaan/rungen? [Y/n]
Y
[-] Creating release Changelog on git@github.com:shakthimaan/rungen via github's API
[+] Succesfully created release with id 37907444
[?] Upload _build/rungen-Changelog.tbz as release asset? [Y/n]
Y
[-] Uploading _build/rungen-Changelog.tbz as a release asset for Changelog via github's API

$ dune-release opam pkg 
[-] Creating opam package description for rungen
[+] Wrote opam package description _build/rungen.Changelog/opam
```
But, `dune-release opam submit` is failing with:
```
$ dune-release opam submit 
[-] Submitting 
[-] Preparing pull request to ocaml/opam-repository
[-] Fetching https://github.com/ocaml/opam-repository.git#master
[-] Checking out a local release-rungen-Changelog branch
[-] Pushing release-rungen-Changelog to https://github.com/ocaml-bench/
dune-release: [ERROR] run ['git' '--git-dir' '.git' 'push' '--force'
       'https://github.com/ocaml-bench/' 'release-rungen-Changelog']: exited with 128
```
Why is it picking `https://github.com/ocaml-bench` which is mentioned in the description section of the opam file?

**Comment by NathanReb** [comment]
The first thing that strikes me is that it picked `Changelog` as the tag earlier, your changelog file must have a format it's not recognizing. I think you change it that way:
```markdown
# Changelog

## 0.1 - January 14, 2021
### Added
- META files for dune release
```
It should then properly pick 0.1 as the version. Note that if you don't want to follow the expected changelog format there are CLI options you can use to pass the version yourself rather than letting dune-release infering it from the changelog.

As to the error your seeing, it seems that the URL to your remote fork is misconfigured. Could you run `dune-release config` and paste the output here so I can better help you fix this?

**Comment by shakthimaan** [comment]
Sorry, what is the expected ChangeLog format? The output of `dune-release config` is as follows:
```
 $ dune-release config
user: ocaml-bench
remote: https://github.com/ocaml-bench/
local: /home/shakthi/opam-repository/
keep-v: <unset>
auto-open: <unset>
```

**Comment by NathanReb** [comment]
We should better document the changelog format but basically it reads the first word of the first header (rank 2 or higher) as the version to release.

It will ignore rank 1 hearders IIRC but it didn't here because it was confused by the header syntax that were mixed:
```
# Changelog
==========
```
either just the leading `#` or the `========` should work but the two together I'm not sure how it's interpreted.

If it doesn't properly ignore the first header please open an issue about this as it might be a bug.

Your remote is indeed misconfigured. What you can see here is your global dune-release configuration, the `remote` should point to your fork of opam-repository so probably something like `git@github.com:shakthimaan/opam-repository`.
You can set it using the following command:
```
dune-release config set remote <url to your fork>
```
I'd advise you to use a `git@github.com:user/repo` URL so that it uses your setup SSH key instead of asking for your password when you want to push there!

**Comment by shakthimaan** [comment]
I now use the version number as specified in the dune-release README and removed the rank1 header:
```
$ (master) cat CHANGES 
## v0.0.1 (2021-02-11)
### Added
- Meta files for dune release 
```
The tag now gets picked up correctly:
```
 $ (master) dune-release tag
[-] Extracting tag from first entry in CHANGES
[-] Using tag "v0.0.1"
[?] Create git tag v0.0.1 for HEAD? [Y/n]
Y
[+] Tagged HEAD with version v0.0.1
```
I have updated ~/.config/dune/release.yml:
```
$ cat ~/.config/dune/release.yml 
user: shakthimaan
remote: git@github.com:shakthimaan/rungen
local: /home/shakthi/opam-repository/
```
So, for every different remote package, I need to update the remote before submitting a request? I now get a `Github API error: "Validation Failed"` when trying to submit the package to opam-repository:
```
 $ dune-release opam submit
[-] Submitting 
[-] Preparing pull request to ocaml/opam-repository
[-] Fetching https://github.com/ocaml/opam-repository.git#master
[-] Checking out a local release-rungen-0.0.1 branch
[-] Pushing release-rungen-0.0.1 to git@github.com:shakthimaan/rungen
[?] Open PR to ocaml/opam-repository? [Y/n]
Y
[-] Opening pull request to merge branch release-rungen-0.0.1 of git@github.com:shakthimaan/rungen into ocaml/opam-repository
dune-release: [ERROR] Could not retrieve pull request URL from response, unexpected Github API error: "Validation Failed"
```

**Comment by shakthimaan** [comment]
Updated `~/.config/dune/release.yml` as required and was able to push the `rungen` package to opam.ocaml.org through https://github.com/ocaml/opam-repository/pull/18176.
