### ISSUE TITLE
tag detection is confused when a branch is named like a tag

### ISSUE THREAD

**Issue by emillon** [ocamllabs/dune-release#451]
Hi,

I was releasing dune 3.6.1. One branch was called 3.6.1 (that's the PR where I prepared the changelog for 3.6.1).
`dune-released` correctly inferred from the changelog that the version was 3.6.1; however it refused to create an annotated tag:

```
dune-release tag
[-] Extracting tag from first entry in CHANGES.md
[-] Using tag "3.6.1"
[-] Nothing to be done: tag already exists.
```

After switching to a different branch and removing the 3.6.1 branch this worked.
I suppose that the function that looks for existing tags is looking at all refs, not just annotated tags.

**Comment by Leonidas-from-XIV** [comment]
It should also look at non-annotated tags (since we support the workflow of using existing tags) but definitely not just any ref.

Looking at the code, it looks up any ref and if it finds it, returns it but lacks checking that this was a tag (so in theory, if your version is an existing commit-id, it would also fail). On the Git side this is an easy fix, on the Mercurial side it could be a bit trickier.

**Comment by 3Rafal** [comment]
Hello, I have prepared a solution that searches for explicitly for tags. I think it's in the spirit of what @Leonidas-from-XIV suggested: #452
